#!/usr/bin/env php
<?php

use Dotenv\Dotenv;
use Codinglabs\Yolo\Yolo;

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

// path to the app root
const BASE_PATH = __DIR__ . '/../../';

Dotenv::createImmutable(BASE_PATH)->load();

$yolo = new Yolo();
$yolo->run();
