name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened, ready_for_review ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4', '8.5']

    name: PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: zip, sqlite3
          coverage: none

      - name: Install composer dependencies
        run: composer install --no-cache --no-ansi --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/pest --parallel --stop-on-failure

  coverage:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04

    name: Coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: zip, sqlite3
          coverage: pcov

      - name: Install composer dependencies
        run: composer install --no-cache --no-ansi --no-interaction --no-progress

      - name: Enforce coverage threshold
        run: vendor/bin/pest --coverage --min=68
